extdir: %kernel.root_dir%/../ext
uploaddir: /.

page:
    account-index: ['account/history','account/favorite','account/watch','basket/mini','catalog/session']
    basket-index: ['basket/standard','basket/related']
    catalog-count: ['catalog/count']
    catalog-detail: ['basket/mini','catalog/stage','catalog/detail','catalog/session']
    catalog-list: ['basket/mini','catalog/filter','catalog/stage','catalog/list']
    catalog-suggest: ['catalog/suggest']
    catalog-stock: ['catalog/stock']
    checkout-confirm: ['checkout/confirm']
    checkout-index: ['checkout/standard']
    checkout-update: ['checkout/update']

resource:
    db:
        adapter: mysql
        host: %database_host%
        port: %database_port%
        database: %database_name%
        username: %database_user%
        password: %database_password%
        stmt: ["SET NAMES 'utf8'", "SET SESSION sql_mode='ANSI'"]
        limit: 2
        opt-persistent: 0

classes:

client:
    html:
        account:
            history:
                url:
                    target: aimeos_shop_account
            favorite:
                url:
                    target: aimeos_shop_account_favorite
            watch:
                url:
                    target: aimeos_shop_account_watch
        catalog:
            count:
                url:
                    target: aimeos_shop_count
            detail:
                url:
                    target: aimeos_shop_detail
            list:
                url:
                    target: aimeos_shop_list
            session:
                pinned:
                    url:
                        target: aimeos_shop_session_pinned
            stock:
                url:
                    target: aimeos_shop_stock
            suggest:
                url:
                    target: aimeos_shop_suggest
        common:
            content:
                baseurl: uploads
            template:
                baseurl: bundles/aimeosshop/elegance
        basket:
            standard:
                url:
                    target: aimeos_shop_basket
        checkout:
            confirm:
                url:
                    target: aimeos_shop_confirm
            standard:
                url:
                    target: aimeos_shop_checkout
                summary:
                    option:
                        terms:
                            url:
                                target: aimeos_shop_terms
                            privacy:
                                url:
                                    target: aimeos_shop_privacy
            update:
                url:
                    target: aimeos_shop_update

controller:
    extjs:
        attribute:
            import:
                text:
                    default:
                        uploaddir: %kernel.root_dir%/../web/uploads
                        fileperms: 0660
            export:
                text:
                    default:
                        exportdir: %kernel.root_dir%/../web/uploads
                        downloaddir: /uploads
        catalog:
            import:
                text:
                    default:
                        uploaddir: %kernel.root_dir%/../web/uploads
                        fileperms: 0660
            export:
                text:
                    default:
                        exportdir: %kernel.root_dir%/../web/uploads
                        downloaddir: /uploads
        media:
            default:
                # Base directory to the document root of the website
                basedir: %kernel.root_dir%/../web
                # Upload related settings
                upload:
                    # Media directory where the uploaded files will be stored, must be relative to the path in "basedir"
                    directory: uploads
                    # Directory permissions (in octal notation) which are applied to newly created directories
                    # dirperms: 0775
                    # File permissions (in octal notation) which are applied to newly created files
                    #fileperms: 0664
                # Mime icon related settings
                mimeicon:
                    # Directory where icons for the mime types stored. Must be relative to the path in "basedir"
                    directory: bundles/aimeosshop/mimeicons
                    # File extension of mime type icons
                    extension: .png
                # Parameter for images
                files:
                    # Allowed image mime types, other image types will be converted
                    # allowedtypes: [image/jpeg, image/png, image/gif ]
                    # Image type to which all other image types will be converted to
                    # defaulttype: jpeg
                    # Maximum width of an image
                    # Image will be scaled up or down to this size without changing the
                    # width/height ratio. A value of "null" doesn't scale the image or
                    # doesn't restrict the size of the image if it's scaled due to a value
                    # in the "maxheight" parameter
                    # maxwidth:
                    # Maximum height of an image
                    # Image will be scaled up or down to this size without changing the
                    # width/height ratio. A value of "null" doesn't scale the image or
                    # doesn't restrict the size of the image if it's scaled due to a value
                    # in the "maxwidth" parameter
                    # maxheight:
                # Parameter for preview images
                preview:
                    # Allowed image mime types, other image types will be converted
                    # allowedtypes: [image/jpeg, image/png, image/gif ]
                    # Image type to which all other image types will be converted to
                    # defaulttype: jpeg
                    # Maximum width of a preview image
                    # Image will be scaled up or down to this size without changing the
                    # width/height ratio. A value of "null" doesn't scale the image or
                    # doesn't restrict the size of the image if it's scaled due to a value
                    # in the "maxheight" parameter
                    # maxwidth: 360
                    # Maximum height of a preview image
                    # Image will be scaled up or down to this size without changing the
                    # width/height ratio. A value of "null" doesn't scale the image or
                    # doesn't restrict the size of the image if it's scaled due to a value
                    # in the "maxwidth" parameter
                    # maxheight: 280
        product:
            import:
                text:
                    default:
                        uploaddir: %kernel.root_dir%/../web/uploads
                        fileperms: 0660
            export:
                text:
                    default:
                        exportdir: %kernel.root_dir%/../web/uploads
                        downloaddir: /uploads

i18n:

madmin:

mshop:
    customer:
        manager:
            password:
                options:
                    format: "%%1$s{%%2$s}"
