parameters:
    controller:
        extjs:
            attribute:
                import:
                    text:
                        default:
                            uploaddir: uploads
                            fileperms: 0660
                export:
                    text:
                        default:
                            downloaddir: uploads
                            exportdir: uploads
            catalog:
                import:
                    text:
                        default:
                            uploaddir: uploads
                            fileperms: 0660
                export:
                    text:
                        default:
                            downloaddir: uploads
                            exportdir: uploads
            media:
                default:
                    # Base directory to the document root of the website
                    basedir: .
                    # Upload related settings
                    upload:
                        # Media directory where the uploaded files will be stored, must be relative to the path in "basedir"
                        directory: uploads
                        # Directory permissions (in octal notation) which are applied to newly created directories
                        # dirperms: 0775
                        # File permissions (in octal notation) which are applied to newly created files
                        #fileperms: 0664
                    # Mime icon related settings
                    mimeicon:
                        # Directory where icons for the mime types stored. Must be relative to the path in "basedir"
                        directory: bundles/aimeosshop/mimeicons
                        # File extension of mime type icons
                        extension: .png
                    # Parameter for images
                    files:
                        # Allowed image mime types, other image types will be converted
                        # allowedtypes: [image/jpeg, image/png, image/gif ]
                        # Image type to which all other image types will be converted to
                        # defaulttype: jpeg
                        # Maximum width of an image
                        # Image will be scaled up or down to this size without changing the
                        # width/height ratio. A value of "null" doesn't scale the image or
                        # doesn't restrict the size of the image if it's scaled due to a value
                        # in the "maxheight" parameter
                        # maxwidth:
                        # Maximum height of an image
                        # Image will be scaled up or down to this size without changing the
                        # width/height ratio. A value of "null" doesn't scale the image or
                        # doesn't restrict the size of the image if it's scaled due to a value
                        # in the "maxwidth" parameter
                        # maxheight:
                    # Parameter for preview images
                    preview:
                        # Allowed image mime types, other image types will be converted
                        # allowedtypes: [image/jpeg, image/png, image/gif ]
                        # Image type to which all other image types will be converted to
                        # defaulttype: jpeg
                        # Maximum width of a preview image
                        # Image will be scaled up or down to this size without changing the
                        # width/height ratio. A value of "null" doesn't scale the image or
                        # doesn't restrict the size of the image if it's scaled due to a value
                        # in the "maxheight" parameter
                        # maxwidth: 360
                        # Maximum height of a preview image
                        # Image will be scaled up or down to this size without changing the
                        # width/height ratio. A value of "null" doesn't scale the image or
                        # doesn't restrict the size of the image if it's scaled due to a value
                        # in the "maxwidth" parameter
                        # maxheight: 280
            product:
                import:
                    text:
                        default:
                            uploaddir: uploads
                            fileperms: 0660
                export:
                    text:
                        default:
                            downloaddir: uploads
                            exportdir: uploads
