aimeos_shop_admin_json:
    path: /admin/do
    defaults: { _controller: AimeosShopBundle:Admin:do, _format: json }

aimeos_shop_admin:
    path: /admin/{site}/{lang}/{tab}
    defaults: { _controller: AimeosShopBundle:Admin:index, site: default, lang: en, tab: 0 }

aimeos_shop_account:
    path: /myaccount
    defaults: { _controller: AimeosShopBundle:Page:account }

aimeos_shop_basket:
    path: /basket
    defaults: { _controller: AimeosShopBundle:Page:basketStandard }

aimeos_shop_count:
    path: /count
    defaults: { _controller: AimeosShopBundle:Catalog:count, _format: js }

aimeos_shop_detail:
    path: /detail/{d_prodid}/{d_name}/{l_pos}
    defaults: { _controller: AimeosShopBundle:Page:catalogDetail, d_name: '', l_pos: 0 }

aimeos_shop_list:
    path: /list/{f_catid}/{f_name}
    defaults: { _controller: AimeosShopBundle:Page:catalogList, f_catid: '', f_name: '' }

aimeos_shop_listsimple:
    path: /suggest
    defaults: { _controller: AimeosShopBundle:Catalog:listSimple, _format: json }

aimeos_shop_stock:
    path: /stock
    defaults: { _controller: AimeosShopBundle:Catalog:stock, _format: js }

aimeos_shop_checkout:
    path: /checkout/{c_step}
    defaults: { _controller: AimeosShopBundle:Page:checkoutStandard, c_step: summary }

aimeos_shop_confirm:
    path: /confirm
    defaults: { _controller: AimeosShopBundle:Page:checkoutConfirm }

aimeos_shop_update:
    path: /update
    defaults: { _controller: AimeosShopBundle:Checkout:update }

aimeos_shop_terms:
    path: /terms
    defaults: { _controller: AimeosShopBundle:Page:terms }

aimeos_shop_privacy:
    path: /privacy
    defaults: { _controller: AimeosShopBundle:Page:privacy }
