aimeos_shop_admin:
    path: /admin
    defaults: { _controller: AimeosShopBundle:Admin:index }

aimeos_shop_admin_check:
    path: /admin_check


aimeos_shop_extadm_file:
    path: /extadm/file
    defaults: { _controller: AimeosShopBundle:Extadm:file }
    methods: [GET]

aimeos_shop_extadm_json:
    path: /extadm/do
    defaults: { _controller: AimeosShopBundle:Extadm:do }
    methods: [POST]

aimeos_shop_extadm:
    path: /extadm/{lang}/{tab}
    defaults: { _controller: AimeosShopBundle:Extadm:index, lang: en, tab: 0 }
    methods: [GET]


aimeos_shop_jqadm_file:
    path: /jqadm/file/{type}
    defaults: { _controller: AimeosShopBundle:Jqadm:file }
    methods: [GET]

aimeos_shop_jqadm_copy:
    path: /jqadm/copy/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jqadm:copy }
    methods: [GET, POST]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]+'

aimeos_shop_jqadm_create:
    path: /jqadm/create/{resource}
    defaults: { _controller: AimeosShopBundle:Jqadm:create }
    methods: [GET, POST]
    requirements:
        resource: '[^0-9]+'

aimeos_shop_jqadm_delete:
    path: /jqadm/delete/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jqadm:delete }
    methods: [GET, POST]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]+'

aimeos_shop_jqadm_get:
    path: /jqadm/get/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jqadm:get }
    methods: [GET]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]+'

aimeos_shop_jqadm_save:
    path: /jqadm/save/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jqadm:save, id: null }
    methods: [POST]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]*'

aimeos_shop_jqadm_search:
    path: /jqadm/search/{resource}
    defaults: { _controller: AimeosShopBundle:Jqadm:search }
    methods: [GET, POST]
    requirements:
        resource: '[^0-9]+'


aimeos_shop_jsonadm_delete:
    path: /jsonadm/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:delete, id: null }
    methods: [DELETE]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]*'

aimeos_shop_jsonadm_get:
    path: /jsonadm/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:get, id: null }
    methods: [GET]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]*'

aimeos_shop_jsonadm_patch:
    path: /jsonadm/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:patch, id: null }
    methods: [PATCH]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]*'

aimeos_shop_jsonadm_post:
    path: /jsonadm/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:post, id: null }
    methods: [POST]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]*'

aimeos_shop_jsonadm_put:
    path: /jsonadm/{resource}/{id}
    defaults: { _controller: AimeosShopBundle:Jsonadm:put, id: null }
    methods: [PUT]
    requirements:
        resource: '[^0-9]+'
        id: '[0-9]*'

aimeos_shop_jsonadm_options:
    path: /jsonadm/{resource}
    defaults: { _controller: AimeosShopBundle:Jsonadm:options, resource: null }
    methods: [OPTIONS]
    requirements:
        resource: '.*'


aimeos_shop_account:
    path: /myaccount
    defaults: { _controller: AimeosShopBundle:Account:index }

aimeos_shop_account_favorite:
    path: /myaccount/favorite/{fav_action}/{fav_id}/{d_name}
    defaults: { _controller: AimeosShopBundle:Account:index, fav_action: '', fav_id: null, d_name: '', d_prodid: null, l_pos: 0 }

aimeos_shop_account_watch:
    path: /myaccount/watch/{wat_action}/{wat_id}/{d_name}
    defaults: { _controller: AimeosShopBundle:Account:index, wat_action: '', wat_id: null, d_name: '', d_prodid: null, l_pos: 0 }

aimeos_shop_account_download:
    path: /myaccount/download/{dl_id}
    defaults: { _controller: AimeosShopBundle:Account:download }


aimeos_shop_basket:
    path: /basket/{b_action}
    defaults: { _controller: AimeosShopBundle:Basket:index, b_action: null }

aimeos_shop_count:
    path: /count
    defaults: { _controller: AimeosShopBundle:Catalog:count, _format: js }

aimeos_shop_detail:
    path: /detail/{d_prodid}/{d_name}/{l_pos}
    defaults: { _controller: AimeosShopBundle:Catalog:detail, d_name: '', l_pos: 0 }

aimeos_shop_list:
    path: /list/{f_catid}/{f_name}
    defaults: { _controller: AimeosShopBundle:Catalog:list, f_catid: null, f_name: '' }

aimeos_shop_session_pinned:
    path: /detail/pin/{pin_action}/{pin_id}/{d_prodid}/{d_name}
    defaults: { _controller: AimeosShopBundle:Catalog:detail, d_name: '', l_pos: 0 }

aimeos_shop_suggest:
    path: /suggest
    defaults: { _controller: AimeosShopBundle:Catalog:suggest, _format: json }

aimeos_shop_stock:
    path: /stock
    defaults: { _controller: AimeosShopBundle:Catalog:stock, _format: js }

aimeos_shop_checkout:
    path: /checkout/{c_step}
    defaults: { _controller: AimeosShopBundle:Checkout:index, c_step: null }

aimeos_shop_confirm:
    path: /confirm/{code}/{orderid}
    defaults: { _controller: AimeosShopBundle:Checkout:confirm, code: null, orderid: null }

aimeos_shop_update:
    path: /update/{code}/{orderid}
    defaults: { _controller: AimeosShopBundle:Checkout:update, code: null, orderid: null }


aimeos_shop_terms:
    path: /terms
    defaults: { _controller: AimeosShopBundle:Page:terms }

aimeos_shop_privacy:
    path: /privacy
    defaults: { _controller: AimeosShopBundle:Page:privacy }
