services:
    aimeos:
        class: Aimeos\ShopBundle\Service\Aimeos
        arguments: ["@service_container"]
    aimeos_context:
        class: Aimeos\ShopBundle\Service\Context
        arguments: ["@request_stack","@service_container"]
    aimeos_i18n:
        class: Aimeos\ShopBundle\Service\I18n
        arguments: ["@service_container"]
    aimeos_page:
        class: Aimeos\ShopBundle\Service\Page
        arguments: ["@service_container"]
    aimeos_view:
        class: Aimeos\ShopBundle\Service\View
        arguments: ["@request_stack","@service_container"]
