sudo: false
dist: xenial
language: php

services:
  - mysql

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

env:
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=3.4.*

matrix:
  fast_finish: true

before_script:
  - echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e "CREATE DATABASE symfony; GRANT ALL ON symfony.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"
  - mysql -e "set global wait_timeout=600"
  - rm composer.lock # Prevent dependency problems
  - composer req "symfony/symfony:${SYMFONY_VERSION}" --no-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls
