sudo: false
language: php

php:
  - 7.3
  - 7.2
  - 7.1

env:
  - SYMFONY_VERSION=4.2.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=3.4.*

matrix:
  fast_finish: true

before_script:
  - echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e "create database symfony;"
  - mysql -e "set global wait_timeout=600"
  - composer self-update
  - rm composer.lock # Prevent dependency problems
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require "symfony/symfony:${SYMFONY_VERSION}"
  - sed -i 's/utf8mb4/utf8/' Resources/config/aimeos_shop.yml

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls
