sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - mysql -e "create database symfony;"
  - mysql -e "set global wait_timeout=600"
  - rm composer.lock # Prevent dependency problems
  - travis_retry composer require "symfony/symfony:${SYMFONY_VERSION}"

script:
  - phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  exclude:
    - php: 5.3
      env: SYMFONY_VERSION=3.0.*
    - php: 5.4
      env: SYMFONY_VERSION=3.0.*
