sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev

before_script:
  - mysql -e "create database symfony;"
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
  - composer install --dev

script: phpunit --coverage-clover coverage.xml

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - env: SYMFONY_VERSION=2.7.*@dev
