parameters:
#    aimeos_shop.example.class: Aimeos\ShopBundle\Example

services:
#    aimeos_shop.example:
#        class: %aimeos_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
